alias zshconfig="nvim ~/.config/zsh/zshrc"
alias lg="lazygit"

alias sudo="sudo -E"
alias c=clear
alias n=nvim
alias p='proxychains'
alias pg='proxychains wget'
alias sup="sudo proxychains"
alias ls="ls --color=tty --group-directories-first"
alias ll="ls -l"
alias sp="pwd | xclip -i"
alias gp='cd $(xclip -o)'
alias lc='leetcode'
alias r='ranger-cd'
alias xi="xclip -selection clipboard"

# tmux
alias t="tmux"
alias tsj="tmux split-window"
alias tsl="tmux split-window -h"
alias tns="tmux new -s"
alias td="tmux detach"
alias ta="tmux attach -t"
alias tls="tmux list-sessions"
alias tlk="tmux list-keys"
alias tlc="tmux list-commands"
alias tlsc="cat /etc/bash.bashrc | grep \"alias t\""
alias tks="tmux kill-session -t"
alias tss="tmux switch -t"
alias trs="tmux rename-session -t"
alias tnw="tmux new-window"
alias tsw="tmux select-window -t"
alias trw="tmux rename-window"

export EDITOR='/usr/bin/nvim'
export PAGER='/usr/bin/less'
export SHELL='/usr/bin/zsh'
export PATH=$PATH:/home/zds/.gem/ruby/2.7.0/bin
# export NVIM_LISTEN_ADDRESS='/tmp/nvim'

function ranger-cd {
  if [[ -f /tmp/ranger-dir ]]; then
    rm /tmp/ranger-dir
  fi
  ranger
  if [[ -f /tmp/ranger-dir ]]; then
    cd `cat /tmp/ranger-dir`
  fi
}

function mkcd {
  mkdir $1
  cd $1
}

function precmd { pwd > /tmp/workingdir }

source ~/.config/zsh/fzf.zsh

if [[ -z $TMUX ]]; then
  tmux
  exit
fi
