alias zshconfig="nvim ~/.config/zsh/zshrc"
alias lg="lazygit"

alias scf=screenfetch
alias sudo="sudo -E"
alias c=clear
alias n=nvim-qt
alias p='proxychains'
alias pg='proxychains wget'
alias sup="sudo proxychains"
alias ll="ls -l"
alias sp="pwd | xclip -i"
alias gp='cd $(xclip -o)'

# tmux
alias t="tmux"
alias tsj="tmux split-window"
alias tsl="tmux split-window -h"
alias tns="tmux new -s"
alias td="tmux detach"
alias ta="tmux attach -t"
alias tls="tmux list-sessions"
alias tlk="tmux list-keys"
alias tlc="tmux list-commands"
alias tlsc="cat /etc/bash.bashrc | grep \"alias t\""
alias tks="tmux kill-session -t"
alias tss="tmux switch -t"
alias trs="tmux rename-session -t"
alias tnw="tmux new-window"
alias tsw="tmux select-window -t"
alias trw="tmux rename-window"

export EDITOR='/usr/bin/nvim'
export PAGER='/usr/bin/less'
export SHELL='/usr/bin/zsh'

# less option
# export LESS='--ignore-case --status-column --LONG-PROMPT --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --no-init --window=-4'
# Set colors for less. Borrowed from https://wiki.archlinux.org/index.php/Color_output_in_console#less .
# export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
# export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
# export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
# export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
# export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
# export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
# export LESS_TERMCAP_ue=$'\E[0m'        # reset underline


# functions
function ranger-cd {
    tempfile="$(mktemp -t tmp.XXXXXX)"
    /usr/bin/ranger --choosedir="$tempfile" "${@:-$(pwd)}"
    test -f "$tempfile" &&
    if [ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]; then
        cd -- "$(cat "$tempfile")"
    fi  
    rm -f -- "$tempfile"
}

function mkcd {
    mkdir $1
    cd $1
}

alias rg="ranger-cd"

source ~/.config/zsh/fzf.zsh

function dateCount {
    target=$(date -d "2020-12-21" +"%j")
    today=$(date +"%j")
    printf "%d days to graduate exam\n" $((target-today))
}

dateCount
