#! /usr/bin/python

import os

def copyFilesFrom(rel_path: str):
    # traverse all files and choose dirs
    for file in os.listdir(rel_path):
        # new_path: directory relative path
        new_path = os.path.sep.join([rel_path, file])
        # if current file is dir:
        # make corresponding home dirs based on current dir
        target_path = '/home/zds/' + new_path
        if os.path.isdir(new_path) and file != '.git':
            # target_dir: directory in home
            if not os.path.exists(target_path):
                os.mkdir(target_path)
            copyFilesFrom(new_path)
        # if current file is file
        # copy the file to dest file
        elif os.path.isfile(new_path) and file != '.gitignore':
            os.system('cp -u {} {}'.format(new_path, target_path))

copyFilesFrom('.')
