#! /bin/bash

[[ $# -ne 1 ]] && printf "usage: $0 <cmd>\n" && exit 1

case $1 in
  "dp")
    xrandr --output DP-1 --auto --primary --output HDMI-2 --off
    ;;
  "hdmi")
    xrandr --output HDMI-2 --auto --primary --output DP-1 --off
    ;;
  "right")
    xrandr --output HDMI-2 --auto --primary --right-of DP-1 --output DP-1 --auto
    ;;
  "left")
    xrandr --output DP-1 --auto --primary --left-of HDMI-2 --output HDMI-2 --auto
    ;;
  "same")
    xrandr --output HDMI-2 --same-as DP-1 --auto
    ;;
  *)
    printf "ERROR: unknown argument\n"
    exit 1
    ;;
esac
