#! /bin/python3
import sys
import shutil
import os

OUTPUT_DIR = '/home/zds/Documents/saved_files'

def save_file(filename: str):
    ext = str.split(filename, '.')[1]
    filetype_dir = OUTPUT_DIR + '/' + ext
    if not os.path.exists(filetype_dir):
        os.mkdir(filetype_dir)
    shutil.copy2(filename, filetype_dir)

def main():
    files = sys.argv[1:]
    for file in files:
        save_file(file)

if __name__ == '__main__':
    main()
