#! /usr/bin/python3

import os
import re
import sys
from datetime import date, timedelta

DATE_REGEX = re.compile(r'^(?:(\d{4})-)?(?:(\d{1,2})-)?(\d{1,2})$')
TODAY = date.today()

# task add '<<effective modern cpp>>' project:Books +python due:2022-05-15
def taskadd():
    task = input('task content: ')
    if task == '':
        print('Error: task content cannot be empty')
        sys.exit(1)
    project = input('project: ')
    tag = input('tag: ')
    due_date = input('date: ')
    taskadd_cmd = 'task add ' + task
    if project != '':
        taskadd_cmd += f' project:{project}'
    if tag != '':
        taskadd_cmd += f' +{tag}'
    flag = False
    due = None
    if due_date != '':
        if re.match(r'^t+$', due_date) is not None:
            due = TODAY + timedelta(len(due_date))
            flag = True
        elif DATE_REGEX.match(due_date) is None:
            due = due_date
            flag = True
        else:
            mo = DATE_REGEX.match(due_date)
            assert(mo is not None)
            cnt = sum(elem is not None for elem in mo.groups())
            assert(cnt <= 3)
            if cnt == 1:
                due = date(TODAY.year, TODAY.month, int(mo.group(3)))
            elif cnt == 2:
                due = date(TODAY.year, int(mo.group(2)), int(mo.group(3)))
            else:
                due = date(int(mo.group(1)), int(mo.group(2)), int(mo.group(3)))
            if due <= TODAY:
                print('Error: past date')
                sys.exit(1)
            flag = True
    if flag == True:
        taskadd_cmd += f' due:{str(due)}'
    # print(taskadd_cmd)
    os.system(taskadd_cmd)

if __name__ == '__main__':
    taskadd()
