#! /usr/bin/python3

import os
import sys


def parse_time_string(time_str):
    if ':' in time_str:
        minutes, seconds = map(int, time_str.split(':'))
        return minutes * 60 + seconds
    else:
        return int(time_str)

def get_output_video_name(input_name):
    prefix, suffix = input_name.split('.')
    return f"{prefix}_truncated.{suffix}"

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage:')
        print(f'\t{sys.argv[0]} start-end video_name')
        sys.exit(1)

    time_period = sys.argv[1]
    input_video_name = sys.argv[2]
    output_video_name = get_output_video_name(input_video_name)
    # print(output_video_name)

    start, end = map(parse_time_string, time_period.split('-'))
    print(start, end)

    cmd = f"ffmpeg -ss {start} -to {end} -i {input_video_name} -c:v copy -c:a copy {output_video_name}"
    print(cmd)
    os.system(cmd)
